include { GET_IMAGES; COMBINE_INFO; GET_GIT_VERSION; GET_PYTHON_VERSION; GET_FASTP_VERSION; GET_UNICYCLER_VERSION; GET_SHOVILL_VERSION; GET_QUAST_VERSION; GET_BWA_VERSION; GET_SAMTOOLS_VERSION; GET_BCFTOOLS_VERSION; GET_POPPUNK_VERSION; GET_MLST_VERSION; GET_KRAKEN2_VERSION; GET_SEROBA_VERSION } from "$projectDir/modules/get_version"

// Alternative workflow for getting versions of pipeline and tools
workflow GET_VERSION {
    GET_IMAGES(Channel.fromPath( "$projectDir/nextflow.config" ))

    GET_GIT_VERSION()
    GET_PYTHON_VERSION()
    GET_FASTP_VERSION()
    GET_UNICYCLER_VERSION()
    GET_SHOVILL_VERSION()
    GET_QUAST_VERSION()
    GET_BWA_VERSION()
    GET_SAMTOOLS_VERSION()
    GET_BCFTOOLS_VERSION()
    GET_POPPUNK_VERSION()
    GET_MLST_VERSION()
    GET_KRAKEN2_VERSION()
    GET_SEROBA_VERSION()

    COMBINE_INFO(
        params.pipeline_version,
        GET_IMAGES.out.json, 
        GET_GIT_VERSION.out, 
        GET_PYTHON_VERSION.out, 
        GET_FASTP_VERSION.out, 
        GET_UNICYCLER_VERSION.out,
        GET_SHOVILL_VERSION.out,
        GET_QUAST_VERSION.out,
        GET_BWA_VERSION.out,
        GET_SAMTOOLS_VERSION.out,
        GET_BCFTOOLS_VERSION.out,
        GET_POPPUNK_VERSION.out,
        GET_MLST_VERSION.out,
        GET_KRAKEN2_VERSION.out,
        GET_SEROBA_VERSION.out
    )

    COMBINE_INFO.out.json.view()
}